
spring.datasource.url=jdbc:mysql://localhost:3306/fakenews
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8099
management.endpoints.web.exposure.include=*
management.endpoint.mappings.enabled=true



google.factcheck.api.key=AIzaSyDn5G27kE3Ac6NNvWbMUOczP-8gOChl0FE




